"""Synthetic incident corpus for IncidentReplay (P12-01 raw evidence).

Every log file used by this project is generated here from a fixed scenario
table, so the bytes — and therefore the sha256 provenance manifest — are
reproducible run after run. Nothing is copied from a real system: hosts,
actors, object names and every IP address are invented, and all addresses
come from ranges reserved for documentation and benchmarking (RFC 5737
192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24 and RFC 2544 198.18.0.0/15).

Two raw formats are emitted so the P12-01 adapters have something real to
parse:

* ``audit.jsonl`` — one JSON object per line, written by the application in
  UTC with explicit ``+00:00`` offsets and a per-scenario ``seq`` counter.
* ``edge-syslog.log`` — RFC 3164-style ``key=value`` lines from an edge
  forwarder. Depending on the scenario the forwarder writes in ``+09:00``
  with a clock that runs ``syslog_skew_seconds`` fast (unsynchronized), or in
  UTC with a synchronized clock. Three origins are therefore possible for an
  event: ``audit`` (application only), ``audit+syslog`` (same ``event_id`` in
  both sources — the dedup/clock-skew case) and ``syslog`` (edge device is the
  *sole* source — the cross-source ordering case).

A scenario also declares events that never reach any file
(``omit_from_files``): they are lost to rotation in the fiction, and the
ingestor must report the ``seq`` hole as uncertainty. Those ids are recorded
in ``groundtruth.py`` as *absent* evidence and must never be cited as support
for a finding.

This module carries no labels. Malicious/benign ground truth lives in
``groundtruth.py`` and is consulted only by the evaluation layer.
"""
import datetime as dt
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).parent
FIXTURE_ROOT = HERE / 'fixtures'
HARDENED_ROOT = HERE / 'fixtures-hardened'

SEED = 7
UTC = dt.timezone.utc
JST = dt.timezone(dt.timedelta(hours=9), 'JST')

FORWARDER_SKEW_SECONDS = 7
CLOCK_SKEW_TOLERANCE_SECONDS = 30

EVENT_TYPE_TO_KIND = {'auth_failure': 'failure', 'auth_success': 'success',
                      'data_access': 'action'}
KIND_TO_EVENT_TYPE = {value: key for key, value in EVENT_TYPE_TO_KIND.items()}

SCENARIO_IDS = (
    'm01-credstuff-exfil',
    'm02-validcreds-staged-exfil',
    'm03-slow-credstuff',
    'm04-insider-known-ip-bulk',
    'b01-admin-bulk-restore',
    'b02-password-expiry-retries',
    'b03-helpdesk-unlock-burst',
    'b04-quarterly-report-export',
    'b05-vpn-reconnect-retries',
)

SCENARIO_SOURCES = {
    'm01-credstuff-exfil': {'host': 'tokyo-edge-01', 'zone': JST,
                            'syslog_skew_seconds': 7},
    'm02-validcreds-staged-exfil': {'host': 'ams-edge-02', 'zone': JST,
                                    'syslog_skew_seconds': 7},
    'm03-slow-credstuff': {'host': 'tokyo-edge-01', 'zone': JST,
                           'syslog_skew_seconds': 7},
    'b01-admin-bulk-restore': {'host': 'blr-edge-03', 'zone': UTC,
                               'syslog_skew_seconds': 0},
}

FIXTURE_README = """# Synthetic incident fixtures — P12 IncidentReplay

Every file in this directory is generated by `scenarios.py` from a fixed
scenario table. **There is no real incident, no real host and no real user
here.** All IP addresses come from ranges reserved for documentation and
benchmarking: RFC 5737 `192.0.2.0/24`, `198.51.100.0/24`, `203.0.113.0/24`
and RFC 2544 `198.18.0.0/15`.

Regenerate (byte-identical; no clock reading and no randomness involved):

```sh
python3 -B -c "import scenarios; scenarios.write_fixtures()"
```

## Layout

- `<scenario-id>/audit.jsonl` — application audit log, JSON Lines, UTC
  (`+00:00`) timestamps, monotonic per-scenario `seq`.
- `<scenario-id>/edge-syslog.log` — RFC 3164-style `key=value` forwarder
  lines. For `m01`/`m02`/`m03` the forwarder writes `+09:00` and its clock
  runs 7 s fast; for `b01` it writes UTC and is synchronized. Some events
  exist *only* here (the edge VPN concentrator is their sole source).
- `<scenario-id>/baseline.json` — asset-owner configuration (known source IPs
  and normal egress per actor). Detector *input*, never a label.
- `adversarial/` — deliberately broken sources: naive timestamps with and
  without a declared host offset, a same-id semantic conflict, and a same-id
  timestamp disagreement beyond the clock-skew tolerance.
- `manifest.json` — sha256, byte size and record count for every file above.

No PCAP, no packet captures, no production data, no personal data.
"""


def _split_order(scenario_ids=SCENARIO_IDS, seed=SEED):
    """Hash-ordered scenario ids (the P09/P10 split discipline)."""
    return sorted(scenario_ids, key=lambda sid: hashlib.sha256(
        ('%d:%s' % (seed, sid)).encode()).hexdigest())


def split(scenario_ids=SCENARIO_IDS, seed=SEED, dev_count=5):
    """Deterministic dev/held-out split by hashed scenario id.

    The split is fixed before any detector is evaluated and is a function of
    the id string only, so no scenario can be moved between splits to flatter
    a metric.
    """
    ordered = _split_order(scenario_ids, seed)
    return {'dev': ordered[:dev_count], 'held_out': ordered[dev_count:],
            'order': ordered, 'seed': seed}


def _event(when, user, ip, kind, action='', bytes_out=0, obj='', ticket='',
           session='', session_type='interactive', factors=('password',),
           origin='audit', omit=False, host=''):
    """One logical audit event (pre-serialization, pre-id assignment)."""
    return {'t': when, 'user': user, 'ip': ip, 'kind': kind,
            'action': action, 'bytes_out': int(bytes_out), 'object': obj,
            'ticket_ref': ticket, 'session_id': session,
            'session_type': session_type,
            'auth_factors': list(factors), 'origin': origin,
            'omit_from_files': omit, 'host': host}


def _auth_failures(start, count, step, user, ip, session, origin='audit',
                   host=''):
    return [_event(start + dt.timedelta(seconds=step * index), user, ip,
                   'failure', action='password_rejected', session=session,
                   factors=[], origin=origin, host=host)
            for index in range(count)]


def _downloads(start, count, step, user, ip, session, size, prefix,
               origin='audit', host=''):
    return [_event(start + dt.timedelta(seconds=step * index), user, ip,
                   'action', action='download', bytes_out=size,
                   obj='%s/part-%02d.parquet' % (prefix, index),
                   session=session, factors=[], origin=origin, host=host)
            for index in range(count)]


def _m01():
    """Credential guessing from an unbaseline IP, then bulk exfiltration."""
    user, ip, known = 'u-1042', '203.0.113.44', '198.51.100.23'
    start = dt.datetime(2026, 1, 4, 9, 0, 0, tzinfo=UTC)
    attack, normal = 's-m01-attacker', 's-m01-normal'
    events = [_event(start - dt.timedelta(seconds=10), user, ip, 'action',
                     action='tunnel_established', obj='vpn/tokyo-edge-01',
                     session=attack, factors=[], origin='syslog',
                     host='tokyo-vpn-01')]
    events.extend(_auth_failures(start, 9, 6, user, ip, attack,
                                 origin='audit+syslog', host='tokyo-edge-01'))
    events.append(_event(start + dt.timedelta(seconds=62), user, ip, 'success',
                         action='login', session=attack,
                         origin='audit+syslog', host='tokyo-edge-01'))
    events.append(_event(start + dt.timedelta(seconds=120), user, ip, 'action',
                         action='object_list', obj='customer-db',
                         session=attack, factors=[]))
    events.extend(_downloads(start + dt.timedelta(seconds=150), 14, 78,
                             user, ip, attack, 60_000_000, 'customer-db'))
    for index in range(4):
        events.append(_event(
            start + dt.timedelta(seconds=900 + 300 * index), user, known,
            'action', action='object_read', bytes_out=4096,
            obj='customer-db/index-%d' % index, session=normal,
            factors=[], omit=index < 2))
    events.append(_event(start + dt.timedelta(seconds=1470), user, ip,
                         'action', action='tunnel_closed',
                         obj='vpn/tokyo-edge-01', session=attack, factors=[],
                         origin='syslog', host='tokyo-vpn-01'))
    baseline = {'users': {user: {'known_ips': [known],
                                 'session_type': 'interactive',
                                 'normal_daily_egress_bytes': 52_428_800}}}
    return events, baseline


def _m02():
    """Password-only login from a new IP, privilege grant, staged exfil."""
    user, ip, known = 'u-2077', '198.18.7.9', '198.51.100.31'
    start = dt.datetime(2026, 1, 6, 2, 14, 0, tzinfo=UTC)
    attack = 's-m02-attacker'
    events = [_event(start, user, ip, 'success', action='login',
                     session=attack, origin='audit+syslog',
                     host='ams-edge-02')]
    events.append(_event(start + dt.timedelta(seconds=60), user, ip, 'action',
                         action='permission_grant', obj='role:data-reader',
                         session=attack, factors=[]))
    events.append(_event(start + dt.timedelta(seconds=120), user, ip, 'action',
                         action='object_list', obj='finance-shares',
                         session=attack, factors=[]))
    events.extend(_downloads(start + dt.timedelta(seconds=180), 12, 110,
                             user, ip, attack, 400_000_000,
                             'finance-shares'))
    baseline = {'users': {user: {'known_ips': [known],
                                 'session_type': 'interactive',
                                 'normal_daily_egress_bytes': 104_857_600}}}
    return events, baseline


def _m03():
    """Slow credential guessing under the burst window, then exfil."""
    user, ip, known = 'u-3311', '203.0.113.90', '198.51.100.47'
    start = dt.datetime(2026, 1, 7, 22, 5, 0, tzinfo=UTC)
    attack = 's-m03-attacker'
    events = _auth_failures(start, 6, 48, user, ip, attack,
                            origin='audit+syslog', host='tokyo-edge-01')
    events.append(_event(start + dt.timedelta(seconds=300), user, ip, 'success',
                         action='login', session=attack,
                         origin='audit+syslog', host='tokyo-edge-01'))
    events.append(_event(start + dt.timedelta(seconds=360), user, ip, 'action',
                         action='object_list', obj='hr-records',
                         session=attack, factors=[]))
    events.extend(_downloads(start + dt.timedelta(seconds=420), 8, 150,
                             user, ip, attack, 90_000_000, 'hr-records'))
    baseline = {'users': {user: {'known_ips': [known],
                                 'session_type': 'interactive',
                                 'normal_daily_egress_bytes': 20_971_520}}}
    return events, baseline


def _m04():
    """Bulk export from a baselined IP with valid SSO and no change ticket."""
    user, ip = 'u-4402', '198.51.100.77'
    start = dt.datetime(2026, 1, 9, 22, 40, 0, tzinfo=UTC)
    attack = 's-m04-insider'
    events = [_event(start, user, ip, 'success', action='login',
                     session=attack, factors=['password'])]
    events.append(_event(start + dt.timedelta(seconds=300), user, ip, 'action',
                         action='object_list', obj='engineering-src',
                         session=attack, factors=[]))
    for index in range(10):
        events.append(_event(
            start + dt.timedelta(seconds=600 + 180 * index), user, ip,
            'action', action='export', bytes_out=250_000_000,
            obj='engineering-src/snapshot-%02d.tar' % index, session=attack,
            factors=[]))
    baseline = {'users': {user: {'known_ips': [ip],
                                 'session_type': 'interactive',
                                 'normal_daily_egress_bytes': 262_144_000}}}
    return events, baseline


def _b01():
    """Legitimate change-ticketed restore: huge volume, baselined service id."""
    user, ip = 'svc-backup', '198.51.100.10'
    start = dt.datetime(2026, 1, 5, 11, 0, 0, tzinfo=UTC)
    session = 's-b01-restore'
    events = [_event(start, user, ip, 'action', action='ticket_open',
                     ticket='CHG-4821', obj='restore/customer-db',
                     session=session, session_type='workload', factors=[],
                     origin='audit+syslog', host='blr-edge-03')]
    events.append(_event(start + dt.timedelta(seconds=120), user, ip, 'success',
                         action='login', session=session,
                         session_type='workload', factors=[],
                         origin='audit+syslog', host='blr-edge-03'))
    for index in range(40):
        events.append(_event(
            start + dt.timedelta(seconds=300 + 225 * index), user, ip,
            'action', action='download', bytes_out=150_000_000,
            obj='restore/customer-db/chunk-%02d' % index, ticket='CHG-4821',
            session=session, session_type='workload', factors=[]))
    baseline = {'users': {user: {'known_ips': [ip],
                                 'session_type': 'workload',
                                 'normal_daily_egress_bytes': 10_737_418_240}}}
    return events, baseline


def _b02():
    """Expired-password retries from the user's own baselined laptop."""
    user, ip = 'u-5510', '198.51.100.44'
    start = dt.datetime(2026, 1, 8, 8, 31, 0, tzinfo=UTC)
    session = 's-b02-user'
    events = _auth_failures(start, 4, 13, user, ip, session)
    events.append(_event(start + dt.timedelta(seconds=70), user, ip, 'success',
                         action='login', session=session,
                         factors=['password', 'totp']))
    events.extend(_downloads(start + dt.timedelta(seconds=180), 2, 60, user,
                             ip, session, 1_048_576, 'reports-q4'))
    baseline = {'users': {user: {'known_ips': [ip],
                                 'session_type': 'interactive',
                                 'normal_daily_egress_bytes': 10_485_760}}}
    return events, baseline


def _b03():
    """Helpdesk service id verifying an unlock: burst of failures, no egress."""
    user, ip = 'svc-helpdesk', '198.51.100.9'
    start = dt.datetime(2026, 1, 8, 15, 2, 0, tzinfo=UTC)
    session = 's-b03-helpdesk'
    events = _auth_failures(start, 5, 5, user, ip, session)
    events.append(_event(start + dt.timedelta(seconds=30), user, ip, 'success',
                         action='login', session=session,
                         session_type='workload', factors=[]))
    events.append(_event(start + dt.timedelta(seconds=90), user, ip, 'action',
                         action='ticket_open', ticket='INC-90117',
                         obj='unlock/u-5510', session=session,
                         session_type='workload', factors=[]))
    baseline = {'users': {user: {'known_ips': [ip],
                                 'session_type': 'workload',
                                 'normal_daily_egress_bytes': 1_048_576}}}
    return events, baseline


def _b04():
    """Quarterly finance export under a ticket, below the egress threshold."""
    user, ip = 'u-6620', '198.51.100.61'
    start = dt.datetime(2026, 1, 6, 14, 0, 0, tzinfo=UTC)
    session = 's-b04-finance'
    events = [_event(start, user, ip, 'action', action='ticket_open',
                     ticket='CHG-4830', obj='reports/q4-consolidated',
                     session=session)]
    events.append(_event(start + dt.timedelta(seconds=60), user, ip, 'success',
                         action='login', session=session,
                         factors=['password', 'totp']))
    events.append(_event(start + dt.timedelta(seconds=180), user, ip, 'action',
                         action='export', bytes_out=320_000_000,
                         obj='reports/q4-consolidated.xlsx', ticket='CHG-4830',
                         session=session, factors=[]))
    events.extend(_downloads(start + dt.timedelta(seconds=420), 3, 90, user,
                             ip, session, 5_242_880, 'reports-q4'))
    baseline = {'users': {user: {'known_ips': [ip],
                                 'session_type': 'interactive',
                                 'normal_daily_egress_bytes': 524_288_000}}}
    return events, baseline


def _b05():
    """VPN client renegotiation: repeated failures from a baselined IP."""
    user, ip = 'u-7731', '198.51.100.88'
    start = dt.datetime(2026, 1, 5, 19, 40, 0, tzinfo=UTC)
    session = 's-b05-vpn'
    events = _auth_failures(start, 6, 20, user, ip, session)
    events.append(_event(start + dt.timedelta(seconds=130), user, ip, 'success',
                         action='login', session=session,
                         factors=['password', 'totp']))
    baseline = {'users': {user: {'known_ips': [ip],
                                 'session_type': 'interactive',
                                 'normal_daily_egress_bytes': 5_242_880}}}
    return events, baseline


_BUILDERS = {
    'm01-credstuff-exfil': _m01,
    'm02-validcreds-staged-exfil': _m02,
    'm03-slow-credstuff': _m03,
    'm04-insider-known-ip-bulk': _m04,
    'b01-admin-bulk-restore': _b01,
    'b02-password-expiry-retries': _b02,
    'b03-helpdesk-unlock-burst': _b03,
    'b04-quarterly-report-export': _b04,
    'b05-vpn-reconnect-retries': _b05,
}


def logical_events(scenario_id):
    """Assign stable ids and seq numbers to a scenario's logical events."""
    if scenario_id not in _BUILDERS:
        raise KeyError('unknown scenario %r' % (scenario_id,))
    raw, baseline = _BUILDERS[scenario_id]()
    events = []
    for index, event in enumerate(raw, start=1):
        event = dict(event)
        event['id'] = '%s-%06d' % (scenario_id.split('-')[0], index)
        event['seq'] = index
        event['scenario'] = scenario_id
        events.append(event)
    return events, baseline


def _json_record(event):
    return {'event_id': event['id'],
            'ts': event['t'].astimezone(UTC).isoformat(),
            'actor': event['user'],
            'src_ip': event['ip'],
            'event_type': KIND_TO_EVENT_TYPE[event['kind']],
            'action': event['action'],
            'bytes_out': event['bytes_out'],
            'object': event['object'],
            'ticket_ref': event['ticket_ref'],
            'session_id': event['session_id'],
            'session_type': event['session_type'],
            'auth_factors': event['auth_factors'],
            'seq': event['seq']}


def syslog_line(event, host=None, zone=None, skew=None, proc='authd',
                pid=4411):
    """Render one logical event as an RFC 3164-style forwarder line."""
    source = SCENARIO_SOURCES.get(event['scenario'], {})
    zone = source.get('zone', JST) if zone is None else zone
    skew = source.get('syslog_skew_seconds', FORWARDER_SKEW_SECONDS) \
        if skew is None else skew
    local = (event['t'] + dt.timedelta(seconds=skew)).astimezone(zone)
    stamp = '%s %2d %02d:%02d:%02d' % (
        local.strftime('%b'), local.day, local.hour, local.minute,
        local.second)
    fields = ['event_id=%s' % event['id'], 'ts=%s' % local.isoformat(),
              'actor=%s' % event['user'], 'src_ip=%s' % event['ip'],
              'event_type=%s' % KIND_TO_EVENT_TYPE[event['kind']],
              'action=%s' % event['action'],
              'bytes_out=%d' % event['bytes_out'],
              'object=%s' % event['object'],
              'ticket_ref=%s' % event['ticket_ref'],
              'session_id=%s' % event['session_id'],
              'session_type=%s' % event['session_type'],
              'auth_factors=%s' % ('|'.join(event['auth_factors'])),
              'seq=%d' % event['seq']]
    return '%s %s %s[%d]: %s' % (
        stamp, host or event['host'] or source.get('host', 'edge-host'),
        proc, pid, ' '.join(fields))


def scenario_files(scenario_id, root=None):
    """Write one scenario's raw sources; return its file manifest rows."""
    root = Path(root) if root else FIXTURE_ROOT
    events, baseline = logical_events(scenario_id)
    directory = root / scenario_id
    directory.mkdir(parents=True, exist_ok=True)

    written = [event for event in events if not event['omit_from_files']]
    audit_events = [event for event in written
                    if event['origin'] in ('audit', 'audit+syslog')]
    syslog_events = [event for event in written
                     if event['origin'] in ('audit+syslog', 'syslog')]

    rows = []
    audit = directory / 'audit.jsonl'
    audit.write_text(''.join(json.dumps(_json_record(event), sort_keys=True)
                             + '\n' for event in audit_events),
                     encoding='utf-8')
    rows.append(_file_row(audit, 'json-audit', scenario_id,
                          len(audit_events)))
    if syslog_events:
        syslog = directory / 'edge-syslog.log'
        syslog.write_text(''.join(syslog_line(event) + '\n'
                                  for event in syslog_events),
                          encoding='utf-8')
        rows.append(_file_row(syslog, 'syslog-kv', scenario_id,
                              len(syslog_events)))

    baseline_path = directory / 'baseline.json'
    baseline_path.write_text(json.dumps(
        dict(baseline, scenario=scenario_id,
             source='asset-owner configuration (synthetic)',
             note='detector input, not a label'),
        indent=2, sort_keys=True) + '\n', encoding='utf-8')
    rows.append(_file_row(baseline_path, 'baseline-config', scenario_id, 0))
    return rows


def _file_row(path, fmt, scenario_id, records):
    data = path.read_bytes()
    return {'path': str(path.relative_to(path.parent.parent)),
            'absolute_path': str(path), 'scenario': scenario_id,
            'format': fmt, 'records': records, 'bytes': len(data),
            'sha256': hashlib.sha256(data).hexdigest()}


def adversarial_files(root=None):
    """Write the deliberately broken sources used to prove rejection paths."""
    root = Path(root) if root else FIXTURE_ROOT
    directory = root / 'adversarial'
    directory.mkdir(parents=True, exist_ok=True)

    def legacy(event_id, host, ts_failure, ts_success):
        return (
            'Jan  4 09:13:22 %s authd[900]: event_id=%s-000001 ts=%s '
            'actor=u-9001 src_ip=203.0.113.200 event_type=auth_failure '
            'action=password_rejected bytes_out=0 object= ticket_ref= '
            'session_id=s-adv session_type=interactive auth_factors= seq=1\n'
            'Jan  4 09:13:30 %s authd[900]: event_id=%s-000002 ts=%s '
            'actor=u-9001 src_ip=203.0.113.200 event_type=auth_success '
            'action=login bytes_out=0 object= ticket_ref= session_id=s-adv '
            'session_type=interactive auth_factors=password seq=2\n'
            % (host, event_id, ts_failure, host, event_id, ts_success))

    naive = directory / 'legacy-naive.log'
    naive.write_text(legacy('adv-naive', 'legacy-host-01',
                            '2026-01-04T09:13:22', '2026-01-04T09:13:30'),
                     encoding='utf-8')
    declared = directory / 'legacy-declared-offset.log'
    declared.write_text(legacy('adv-declared', 'legacy-host-02',
                               '2026-01-04T09:13:22', '2026-01-04T09:13:30'),
                        encoding='utf-8')

    base = json.dumps({'event_id': 'm01-000002',
                       'ts': '2026-01-04T09:00:00+00:00', 'actor': 'u-1042',
                       'src_ip': '203.0.113.44', 'event_type': 'auth_failure',
                       'action': 'password_rejected', 'bytes_out': 0,
                       'object': '', 'ticket_ref': '',
                       'session_id': 's-m01-attacker',
                       'session_type': 'interactive', 'auth_factors': [],
                       'seq': 2}, sort_keys=True)
    conflicting = directory / 'conflicting-same-id.jsonl'
    conflicting.write_text(
        base + '\n' + json.dumps(dict(json.loads(base), actor='u-9999',
                                      src_ip='192.0.2.99'),
                                 sort_keys=True) + '\n', encoding='utf-8')

    skewed = directory / 'skew-beyond-tolerance.jsonl'
    skewed.write_text(
        base + '\n' + json.dumps(dict(json.loads(base),
                                      ts='2026-01-04T09:10:00+00:00'),
                                 sort_keys=True) + '\n', encoding='utf-8')

    mixed = directory / 'mixed-naive-and-offset.jsonl'
    mixed_rows = [
        dict(json.loads(base), event_id='adv-mixed-000001', seq=1,
             ts='2026-01-04T09:00:00+00:00'),
        dict(json.loads(base), event_id='adv-mixed-000002', seq=2,
             ts='2026-01-04T09:05:00'),
        dict(json.loads(base), event_id='adv-mixed-000003', seq=3,
             ts='2026-01-04T18:10:00+09:00'),
    ]
    mixed.write_text(''.join(json.dumps(row, sort_keys=True) + '\n'
                             for row in mixed_rows), encoding='utf-8')

    return [_file_row(path, 'adversarial', 'adversarial', 0) for path in
            (naive, declared, conflicting, skewed, mixed)]


def write_fixtures(root=None):
    """Materialize the whole corpus; returns the fixture manifest."""
    root = Path(root) if root else FIXTURE_ROOT
    root.mkdir(parents=True, exist_ok=True)
    rows = []
    for scenario_id in SCENARIO_IDS:
        rows.extend(scenario_files(scenario_id, root))
    rows.extend(adversarial_files(root))
    (root / 'README.md').write_text(FIXTURE_README, encoding='utf-8')
    manifest = {'generated_by': 'scenarios.write_fixtures()',
                'synthetic': True, 'real_incident': False,
                'seed': SEED, 'files': rows,
                'forwarder_clock_skew_seconds': FORWARDER_SKEW_SECONDS,
                'clock_skew_tolerance_seconds': CLOCK_SKEW_TOLERANCE_SECONDS,
                'scenario_sources': {
                    key: {'host': value['host'],
                          'zone_utc_offset': str(value['zone'].utcoffset(
                              dt.datetime(2026, 1, 1, tzinfo=UTC))),
                          'syslog_skew_seconds':
                              value['syslog_skew_seconds']}
                    for key, value in sorted(SCENARIO_SOURCES.items())},
                'split': split(),
                'corpus_sha256': hashlib.sha256(
                    '\n'.join(row['sha256'] for row in rows).encode()
                ).hexdigest()}
    (root / 'manifest.json').write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + '\n',
        encoding='utf-8')
    return manifest


def load_baseline(scenario_id, root=None):
    """Asset-owner baseline config for one scenario (detector input)."""
    root = Path(root) if root else FIXTURE_ROOT
    path = root / scenario_id / 'baseline.json'
    return json.loads(path.read_text(encoding='utf-8'))


def scenario_source_files(scenario_id, root=None):
    """Raw log files (not the baseline config) for one scenario."""
    root = Path(root) if root else FIXTURE_ROOT
    return [path for path in sorted((root / scenario_id).iterdir())
            if path.name in ('audit.jsonl', 'edge-syslog.log')
            and not path.name.startswith('._')]


def absent_event_ids(scenario_id):
    """Ids declared by the scenario but written to no file (rotation loss)."""
    events, _ = logical_events(scenario_id)
    return [event['id'] for event in events if event['omit_from_files']]


if __name__ == '__main__':
    print(json.dumps(write_fixtures(), indent=2, sort_keys=True))
